### PR TITLE
Allow overriding base order for react-style styles

### PR DESCRIPTION
**Pull request by jscheid**
This feature is intended for increasing specificity of styles added using react-style, for example because react-style is combined with an external stylesheet that needs to be overridden.

Another way of setting base specificity would be adding a corresponding argument to the ReactStyle call.  However this would mean that when specifying multiple styles in an array, you can't rely on later styles overriding earlier ones anymore.  Therefore this is implemented as a per-element property.

### CODE REVIEW

**Comment by SanderSpies** [comment]
Yeah, we definitely need something like this - but perhaps in a bit different form.

- rename the property to `__dangerouslySetStylesPrefix` (or something similar) to align with `__dangerouslySetInnerHTML` 
- I think the user should be able to enter a CSS selector here, that will be placed before the React Style selector

**Comment by jscheid** [comment]
To clarify, this is intended for a situation where you're using a third-party stylesheet that defines something like

    ul.foo > li.bar { ... };

and you want to add styles to that `li` element, so you need a way to tell react-style that the base specificity needs to be higher (3 in this case). I don't see how setting a CSS selector would help here? Also I'm not sure if this is really so dangerous. It seems more perilous *not* to change the base specificity in this case :-)

**Comment by SanderSpies** [comment]
Sorry, but this doesn't really help with overriding selectors with id's.
Op 17 mrt. 2015 12:24 schreef "Julian Scheid" <notifications@github.com>:

**Comment by jscheid** [comment]
As discussed on IRC, a more flexible solution is to have a user-specified prefix that gets prepended to all selectors generated by react-style. Closing this.

**Pull request closed without merging**
